# Generated by Django 3.2.5 on 2021-07-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azania', '0002_alter_appointments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
